name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      
      - name: Install deps
        run: |
          sudo apt install libglib-perl liblocale-gettext-perl libxml-simple-perl libwww-mechanize-perl \
            libwww-perl libnet-dbus-perl imagemagick perlmagick libx11-protocol-perl librsvg2-common xdg-utils \
            procps librsvg2-2 libproc-processtable-perl libpath-class-perl libjson-perl libjson-maybexs-perl \
            libfile-which-perl libfile-spec-perl libfile-basedir-perl libfile-copy-recursive-perl \
            libproc-simple-perl libsort-naturally-perl libnumber-bytes-human-perl libglib-object-introspection-perl            curl -L http://cpanmin.us | perl - --sudo App::cpanminus
          
          sudo cpanm --installdeps --notest .
          
      - name: Run tests
        run: TEST_APP_SHUTTER_PATH=$(pwd) prove -I share/shutter/resources/modules/ -I t/lib t -r
